# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f78321f43169cd3209c11c68015d2330c55639abb65eb43eeec645d7a24c373b2fe6a01ac7dba5147a2c5fc995a2efedb08bb3363f1d79fd342f7ea1afa92b1

test:
  secret_key_base: 17f3ffbd9e2cd8e17150c9738066c86fb2cfad9cddb0b3f5b4cbab9350d70207b426168b8ddc292bb37a0b2b0a1c578363335938254405e3fc7b00b6bb13b0f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
